import { AgentResult, CostModelResult, PartnerRanking, SlaRiskResult, VolumeForecast } from '@common/types';
import { runPrompt } from './base.agent';

export interface ExecutiveSummaryInput {
  hubId: number;
  areaId: number;
  weightGrams: number;
  parcelValue: number;
  slaDays: number;
  volumeForecast: VolumeForecast;
  costModels: CostModelResult[];
  slaRisks: SlaRiskResult[];
  partnerRanking: PartnerRanking;
  dispatchType: '3PL' | '4PL';
}

const SYSTEM_PROMPT = `You are an executive operations advisor for RedX, a courier company in Bangladesh.
You will receive analysis from multiple AI agents about a dispatch decision for a hub/area.
Write a concise, human-readable decision report for operations managers.

IMPORTANT terminology: "3PL", "Shopup", "Shopup Internal", and "Shopup (Internal)" all refer to
the SAME thing — RedX's own in-house delivery fleet. Never suggest switching between these names
as they are identical. Only suggest switching to a named external 4PL partner (e.g. Steadfast, Pathao).

Your report must include:
1. Recommended dispatch type (3PL or 4PL) and partner
2. Key reason for the recommendation
3. Expected margin impact (BDT per parcel)
4. SLA risk level and main risk factor
5. One actionable next step

Keep it under 150 words. Write in plain English, no jargon. Return plain text (no JSON, no markdown).`;

export async function runExecutiveSummaryAgent(
  input: ExecutiveSummaryInput
): Promise<AgentResult<string>> {
  const { hubId, areaId, weightGrams, parcelValue, slaDays, volumeForecast, costModels, partnerRanking, dispatchType } = input;

  const recommendedCost = costModels.find(c => c.scenario === (dispatchType === '4PL' ? '4PL' : '3PL'));

  // For 3PL decisions the partner is always Shopup Internal, not the 4PL candidate
  const resolvedPartner = dispatchType === '4PL'
    ? partnerRanking.optimal_partner_name
    : 'Shopup (Internal)';
  const resolvedBackup = dispatchType === '4PL'
    ? (partnerRanking.backup_partner_name ?? 'None')
    : 'N/A';

  // For 4PL: show which external partner was evaluated and its risk
  // For 3PL: only show the evaluated partner's risk score as reason for rejection — no partner name to avoid Shopup/Shopup Internal confusion
  const slaSection = dispatchType === '4PL'
    ? `Selected 4PL partner SLA risk:
- Partner: ${partnerRanking.optimal_partner_name}
- Risk score: ${partnerRanking.sla_risk_score}/100
- Confidence: ${partnerRanking.confidence}%`
    : `4PL evaluation result (reason for using in-house fleet):
- Best available 4PL risk score: ${partnerRanking.sla_risk_score}/100 (threshold: 60 — must be below to use 4PL)
- 4PL candidate: ${partnerRanking.optimal_partner_name ?? 'none found'}`;

  const userPrompt = `Hub: ${hubId} | Area: ${areaId}
Parcel: ${weightGrams}g, value BDT ${parcelValue}, required SLA: ${slaDays} day${slaDays !== 1 ? 's' : ''}
Dispatch decision: ${dispatchType}
Recommended partner: ${resolvedPartner} (confidence: ${partnerRanking.confidence}%)
Backup partner: ${resolvedBackup}

Volume forecast:
- Daily avg: ${volumeForecast.predicted_daily_avg} parcels/day
- 90-day total: ${volumeForecast.forecast_90d_total} parcels
- Trend: ${volumeForecast.trend}

Margin analysis (${dispatchType} scenario):
- Avg margin per parcel: BDT ${recommendedCost?.avg_margin_per_parcel ?? 'N/A'}
- Delta vs current: BDT ${recommendedCost?.margin_delta_vs_current ?? 'N/A'}

${slaSection}

Write the executive summary report now.`;

  const summary = await runPrompt(SYSTEM_PROMPT, userPrompt);

  return {
    data: summary.trim(),
    reasoning: 'Generated by synthesizing volume, cost, SLA, and partner evaluation data.',
    confidence: partnerRanking.confidence,
  };
}
