import { AgentResult, CostModelResult, PartnerRanking, SlaRiskResult, VolumeForecast } from '@common/types';
import { runPrompt } from './base.agent';

export interface ExecutiveSummaryInput {
  hubId: number;
  areaId: number;
  weightGrams: number;
  parcelValue: number;
  slaDays: number;
  volumeForecast: VolumeForecast;
  costModels: CostModelResult[];
  slaRisks: SlaRiskResult[];
  partnerRanking: PartnerRanking;
  dispatchType: '3PL' | '4PL';
}

const SYSTEM_PROMPT = `You are an executive operations advisor for RedX, a courier company in Bangladesh.
You will receive analysis from multiple AI agents about a dispatch decision for a hub/area.
Write a concise, human-readable decision report for operations managers.

Your report must include:
1. Recommended dispatch type (3PL or 4PL) and partner
2. Key reason for the recommendation
3. Expected margin impact (BDT per parcel)
4. SLA risk level and main risk factor
5. One actionable next step

Keep it under 150 words. Write in plain English, no jargon. Return plain text (no JSON, no markdown).`;

export async function runExecutiveSummaryAgent(
  input: ExecutiveSummaryInput
): Promise<AgentResult<string>> {
  const { hubId, areaId, weightGrams, parcelValue, slaDays, volumeForecast, costModels, slaRisks, partnerRanking, dispatchType } = input;

  const recommendedCost = costModels.find(c => c.scenario === (dispatchType === '4PL' ? '4PL' : '3PL'));
  const topRisk = slaRisks.sort((a, b) => b.risk_score - a.risk_score)[0];

  const userPrompt = `Hub: ${hubId} | Area: ${areaId}
Parcel: ${weightGrams}g, value BDT ${parcelValue}, required SLA: ${slaDays} day${slaDays !== 1 ? 's' : ''}
Dispatch decision: ${dispatchType}
Recommended partner: ${partnerRanking.optimal_partner_name} (confidence: ${partnerRanking.confidence}%)
Backup partner: ${partnerRanking.backup_partner_name ?? 'None'}

Volume forecast:
- Daily avg: ${volumeForecast.predicted_daily_avg} parcels/day
- 90-day total: ${volumeForecast.forecast_90d_total} parcels
- Trend: ${volumeForecast.trend}

Margin analysis (${dispatchType} scenario):
- Avg margin per parcel: BDT ${recommendedCost?.avg_margin_per_parcel ?? 'N/A'}
- Delta vs current: BDT ${recommendedCost?.margin_delta_vs_current ?? 'N/A'}

Top SLA risk:
- Partner: ${topRisk?.partner_name ?? 'N/A'}
- Risk level: ${topRisk?.risk_level ?? 'N/A'}
- Breach probability: ${topRisk?.breach_probability ?? 'N/A'}%

Write the executive summary report now.`;

  const summary = await runPrompt(SYSTEM_PROMPT, userPrompt);

  return {
    data: summary.trim(),
    reasoning: 'Generated by synthesizing volume, cost, SLA, and partner evaluation data.',
    confidence: partnerRanking.confidence,
  };
}
